######################################################################
#
# System Configuration
#
######################################################################
ifeq (${PWOS}, darwin)
    SHARED_BASENAME = lib${1}.dylib

    SHARED_LDFLAGS += -dynamiclib
    # Some of our libraries reference symbols that are defined in other libraries.
    # For example, the main library references renderers, but those are defined in
    # other libraries, and we don't know which library will provide the library at
    # the time the main library is being built.
    SHARED_LDFLAGS += -undefined dynamic_lookup
    # We want the library to be searched for on the runtime load path.
    SHARED_LDFLAGS += -Wl,-install_name,@rpath/$(shell basename ${target})

    OPENGL_CXXFLAGS = -I/System/Library/Frameworks/OpenGL.framework/Headers
    OPENGL_LIBS = -framework OpenGL

    # clang++ defaults to using this directory, but g++ via MacPorts doesn't.
    CXXFLAGS += -I/usr/local/include
else
    SHARED_BASENAME = lib${1}.so

    SHARED_LDFLAGS = -fPIC -shared

    OPENGL_CXXFLAGS = -I/usr/include/GL
    OPENGL_LIBS = -lGL -lGLU

    CXXFLAGS += -fPIC
endif

LD=${CXX}

CXXFLAGS += -g -std=c++11 -c -MMD -Wall

# Flags required for linking to a library in ${PWLIB}
PWLIB_LDFLAGS = -Wl,-rpath,${PWLIB} -L${PWLIB} 
ifeq (${PWOS}, bigred2)
    PWLIB_LDFLAGS += -Wl,-dy
endif

DLOPEN_LIBS = -ldl
GSL_LIBS = -lgsl -lgslcblas
ZIP_LIBS = -lz

######################################################################
#
# Optimization
#
######################################################################
ifeq (${PWOPT}, optimized)
    CXXFLAGS += -O2
endif

######################################################################
#
# OpenMP
#
######################################################################
ifeq (${PWOMP}, False)
    OMP_CXXFLAGS = -Wno-unknown-pragmas
else
    OMP_CXXFLAGS = -fopenmp
    ifeq (${PWTOOLCHAIN}, gcc)
        OMP_LIBS = -lgomp
    endif
endif

######################################################################
#
# QMake Flags/Macros
#
######################################################################
ifeq (${PWOS}, darwin)
    # Command-line spec
    QMAKE=${PWQMAKE} -spec macx-llvm

    # When we build a library, we want to specify it's on the runtime linker path.
    QMAKE_LFLAGS_SONAME = -Wl,-install_name,@rpath/
    
    # Make edits to the qmake-generated Makefile for cases where a convenient
    # or reliable official mechanism isn't currently available.
    FIXUP_QT_MAKEFILE = sed -e 's/-mmacosx-version-min=[[:digit:]\.]*//' -i "" ${1} ;\
                        sed -e 's/export MACOSX_DEPLOYMENT_TARGET.*//' -i "" ${1} ;
else
    QMAKE=${PWQMAKE}
    
    # no-op
    FIXUP_QT_MAKEFILE = 
endif

######################################################################
#
# Project Directory Structure
#
######################################################################
PWSRC=${PWHOME}/src
PWBIN=${PWHOME}/bin
PWBLD=${PWHOME}/.bld
PWLIB=${PWHOME}/lib

TARGET_MAK=${PWHOME}/etc/bld/target.mak

######################################################################
#
# Target Source Location
#
######################################################################
APP_SRC=${PWSRC}/app
LIBRARY_SRC=${PWSRC}/library
QTRENDERER_SRC=${PWSRC}/qtrenderer
CALCCOMP_SRC=${PWSRC}/tools/CalcComplexity
RANCHECK_SRC=${PWSRC}/tools/rancheck
PWMOVIEPLAYER_SRC=${PWSRC}/tools/PwMoviePlayer
PROPUTIL_SRC=${PWSRC}/tools/proputil
PMVUTIL_SRC=${PWSRC}/tools/pmvutil
QTCLUST_SRC=${PWSRC}/tools/clustering
OMPTEST_SRC=${PWSRC}/tools/omp_test
PASSIVE_SRC=${PWSRC}/tools/passive
NEURONS_SRC=${PWSRC}/tools/neurons
EXPANSION_SRC=${PWSRC}/tools/expansion
BIFURCATION_SRC=${PWSRC}/tools/bifurcation
TIMESERIES_SRC=${PWSRC}/tools/timeseries
CPPPROPS_SRC=.

######################################################################
#
# Target Name
#
######################################################################
APP_TARGET_NAME=Polyworld
LIBRARY_TARGET_NAME=polyworld
QTRENDERER_TARGET_NAME=pwqtrenderer
CALCCOMP_TARGET_NAME=CalcComplexity
RANCHECK_TARGET_NAME=rancheck
PWMOVIEPLAYER_TARGET_NAME=PwMoviePlayer
PROPUTIL_TARGET_NAME=proputil
PMVUTIL_TARGET_NAME=pmvutil
QTCLUST_TARGET_NAME=qt_clust
OMPTEST_TARGET_NAME=omp_test
PASSIVE_TARGET_NAME=passive
NEURONS_TARGET_NAME=neurons
EXPANSION_TARGET_NAME=expansion
BIFURCATION_TARGET_NAME=bifurcation
TIMESERIES_TARGET_NAME=timeseries
CPPPROPS_TARGET_NAME=cppprops

######################################################################
#
# Target Path
#
######################################################################
APP_TARGET=${PWHOME}/${APP_TARGET_NAME}
LIBRARY_TARGET=${PWLIB}/$(call SHARED_BASENAME,${LIBRARY_TARGET_NAME})
QTRENDERER_TARGET=${PWLIB}/$(call SHARED_BASENAME,${QTRENDERER_TARGET_NAME})
CALCCOMP_TARGET=${PWBIN}/${CALCCOMP_TARGET_NAME}
RANCHECK_TARGET=${PWBIN}/${RANCHECK_TARGET_NAME}
PWMOVIEPLAYER_TARGET=${PWBIN}/${PWMOVIEPLAYER_TARGET_NAME}
PROPUTIL_TARGET=${PWBIN}/${PROPUTIL_TARGET_NAME}
PMVUTIL_TARGET=${PWBIN}/${PMVUTIL_TARGET_NAME}
QTCLUST_TARGET=${PWBIN}/${QTCLUST_TARGET_NAME}
OMPTEST_TARGET=${PWBIN}/${OMPTEST_TARGET_NAME}
PASSIVE_TARGET=${PWBIN}/${PASSIVE_TARGET_NAME}
NEURONS_TARGET=${PWBIN}/${NEURONS_TARGET_NAME}
EXPANSION_TARGET=${PWBIN}/${EXPANSION_TARGET_NAME}
BIFURCATION_TARGET=${PWBIN}/${BIFURCATION_TARGET_NAME}
TIMESERIES_TARGET=${PWBIN}/${TIMESERIES_TARGET_NAME}
CPPPROPS_TARGET=./$(call SHARED_BASENAME,${CPPPROPS_TARGET_NAME})

######################################################################
#
# Target Intermediate Build Dir
#
######################################################################
APP_BLDDIR=${PWBLD}/app
LIBRARY_BLDDIR=${PWBLD}/library
QTRENDERER_BLDDIR=${PWBLD}/${QTRENDERER_TARGET_NAME}
CALCCOMP_BLDDIR=${PWBLD}/${CALCCOMP_TARGET_NAME}
RANCHECK_BLDDIR=${PWBLD}/${RANCHECK_TARGET_NAME}
PWMOVIEPLAYER_BLDDIR=${PWBLD}/${PWMOVIEPLAYER_TARGET_NAME}
PROPUTIL_BLDDIR=${PWBLD}/${PROPUTIL_TARGET_NAME}
PMVUTIL_BLDDIR=${PWBLD}/${PMVUTIL_TARGET_NAME}
QTCLUST_BLDDIR=${PWBLD}/${QTCLUST_TARGET_NAME}
OMPTEST_BLDDIR=${PWBLD}/${OMPTEST_TARGET_NAME}
PASSIVE_BLDDIR=${PWBLD}/${PASSIVE_TARGET_NAME}
NEURONS_BLDDIR=${PWBLD}/${NEURONS_TARGET_NAME}
EXPANSION_BLDDIR=${PWBLD}/${EXPANSION_TARGET_NAME}
BIFURCATION_BLDDIR=${PWBLD}/${BIFURCATION_TARGET_NAME}
TIMESERIES_BLDDIR=${PWBLD}/${TIMESERIES_TARGET_NAME}
CPPPROPS_BLDDIR=.

######################################################################
#
# Target Flags (e.g. LIBRARY_* is for other targets to link to LIBRARY)
#
######################################################################
CPPPROPS_CXXFLAGS=-DPWHOME="\"${PWHOME}\"" -DCPPPROPS_TARGET="\"${CPPPROPS_TARGET}\""

LIBRARY_CXXFLAGS = -I${LIBRARY_SRC}
LIBRARY_LIBS = -l${LIBRARY_TARGET_NAME}

QTRENDERER_CXXFLAGS = -I${QTRENDERER_SRC}
QTRENDERER_LIBS = -l${QTRENDERER_TARGET_NAME}
