#!/bin/bash

cd `dirname $0`/../..

rm -rf regression
mkdir regression

if [ -e worldfile ]; then
   if [ ! -e .worldfile.regression ]; then
       mv worldfile .worldfile.regression
   fi
fi


if scripts/regression/__run.sh $*; then
    # test was successful, so cleanup
    rm -rf regression
    if [ -e .worldfile.regression ]; then
	mv .worldfile.regression worldfile
    fi
fi