conf=../../../Makefile.conf
include ${conf}

target=${EXPANSION_TARGET}
blddir=${EXPANSION_BLDDIR}

cxxflags=${CXXFLAGS} ${OPENGL_CXXFLAGS} ${LIBRARY_CXXFLAGS}
ldflags=${PWLIB_LDFLAGS}
libs=${OPENGL_LIBS} ${QTRENDERER_LIBS} ${LIBRARY_LIBS}

include ${TARGET_MAK}
