#!/usr/bin/env bash

set -e

. $(dirname $0)/__util

check_pwd

if ! is_wiki_downloaded; then
    err -e "Error: Wiki is not present in local repo.\n"\
           "To download the wiki for this branch, execute './scripts/wiki/checkout'\n"\
           "To download the latest wiki version, execute  './scripts/wiki/pull'"
fi

if [ ! -d ${FLAVOR_DIR} ]; then
    echo "Downloading converter."
    mkdir -p $(dirname ${FLAVOR_DIR})
    git clone ${FLAVOR_REPO} ${FLAVOR_DIR}
fi

rm -rf ${HTML_DIR}
mkdir -p ${HTML_DIR}

for md in ${MD_DIR}/*.md; do
    html="${HTML_DIR}/$(basename ${md%.md})"
    echo "Converting $md into $html"
    ruby ${FLAVOR_DIR}/flavor.rb $md > $html
done

echo "Conversion complete."
