#!/bin/bash

function err() {
   echo "$*" >&2
   exit 1
}

function usage() {
    echo "usage: "`basename $0`" [--gdb] rundir agentNumber"
    exit 1
}

if [ "$1" == "--gdb" ]; then
    useGdb=true
    shift
fi

if [ $# != 2 ]; then
    usage
fi

rundir="$1"
agentNumber="$2"


if [ ! -e ./scripts/`basename $0` ]; then
   err 'Must be invoked from polyworld home dir'
   exit 1
fi

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT
function ctrl_c() {
    # If the user cancels the simulator with ctrl-c, we want to
    # recover so we restore the worldfile and seed file.
    
    : # no-op
}


if [ -e ./genomeSeeds.txt ]; then
    seeds_save=`mktemp genomeSeeds.txt.XXXXXXXX`
    echo "Saving existing ./genomeSeeds.txt to $seeds_save"
    mv ./genomeSeeds.txt $seeds_save
fi

if [ -e ./run ]; then
    run_save=`mktemp run.XXXXXXXX`
    rm $run_save
    echo "Saving existing ./run to $run_save"
    mv ./run $run_save
fi

if ./scripts/genomeSeed --agent $agentNumber $rundir; then
    cp $rundir/normalized.wf /tmp/debugBrain.wf
    if ./scripts/wfutil edit /tmp/debugBrain.wf \
	MaxSteps=10000 \
	EndOnPopulationCrash=False \
	MinAgents=1 \
	InitAgents=1 \
	SeedAgents=1 \
	SeedMutationProbability=0.0 \
	SeedGenomeFromRun=True \
	"Domains[*].ProbabilityOfMutatingSeeds=0.0"
    then
	if [ "$useGdb" == "true" ]; then
	    gdb --args ./Polyworld --debug
	else
	    ./Polyworld --debug /tmp/debugBrain.wf
	fi

	rm -rf run
    fi
fi

if [ ! -z "$seeds_save" ]; then
    mv $seeds_save ./genomeSeeds.txt
fi

if [ ! -z "$run_save" ]; then
    mv $run_save ./run
fi
