#!/usr/bin/env python

import sys

import common_logs


rundir = sys.argv[1]

lifespans = common_logs.LifeSpans( rundir )

out = open( 'genomeSeeds.txt', 'w' )

for agent in lifespans.getAllWithDeathReason( 'SIMEND' ):
    out.write(rundir + '/genome/genome_' + str(agent) + '.txt\n' )

out.close()
