#!/usr/bin/env python
import sys, getopt, os
import common_functions
########################################################################################################
# CONFIGURABLE OPTIONS
FILENAME="genome/AdamiComplexity-summary.txt"
GNUPLOT_ylabel="Genomic Consistency (bits)"
GNUPLOT_title="Genomic consistency over time"
plotOnebit, plotTwobit, plotFourbit = True, False, False
LINEWIDTH=1.5
MEANLINEWIDTH=3
tempfilename = "/tmp/,plotAdamiComplexity_%s.gnuplot" % ( os.getpid() )
# Don't modify anything beneath here
GNUPLOT_ymin, GNUPLOT_ymax, GNUPLOT_xmin, GNUPLOT_xmax = '*','*','*','*'
#GNUPLOT_KEY="at screen 0.5,0.960 center horizontal spacing 1 width 0"
#GNUPLOT_KEY="outside"
GNUPLOT_KEY="at screen 1,1 right horizontal spacing 1"
GNUPLOT_BARE_TITLES=0
COLOR=False
MEAN=False
RunTitles=True
MeanTitles=True
########################################################################################################

FILENAMES = []
GNUPLOT_TITLES, GNUPLOT_LINETYPES = {}, {}
GNUPLOT_MEAN_TITLES = [ "Driven", "Passive" ]

def print_usage_and_exit():
	print """
	This script will output the graph of the AdamiComplexity of any given number of run/ directories.

	Useage: ./plotAdamiComplexity [-124] run1/ [run2/]

	Options:
	-1		Plot 1-bit (default on)
	-2		Plot 2-bit (default off)
	-4		Plot 4-bit (default off)
	-b		Use 'bare' titles (don't append n-bit to the end)
	-t"<string>"	Title of the plot
	-x<int>		lowest X-value to show
	-X<int>		highest X-value to show
	-y<int>		lowest Y-value to show
	-Y<int>		highest Y-value to show
	-K"<string>"	GNUPLOTcommands for positioning the key
	"""
	sys.exit(1)


def check_parameters( argv ):
	global plotOnebit, plotTwobit, plotFourbit, FILENAMES, FILENAME, GNUPLOT_TITLES, GNUPLOT_title, GNUPLOT_ymin, GNUPLOT_ymax, GNUPLOT_xmin, GNUPLOT_xmax, GNUPLOT_LINETYPES, GNUPLOT_KEY, GNUPLOT_BARE_TITLES, COLOR, MEAN, RunTitles, MeanTitles

	# getopt insists that all parameters come BEFORE the arguments.  So lets ensure that now.
	for element in argv[:]:
		if element.startswith('-'):     # is this element a parameter?
			argv.remove(element)
			argv.insert(0, element) # put the element at the beginning of the list

	try: opts, args = getopt.getopt( argv, "124tbcmRM:x:X:y:Y:K:")
	except getopt.GetoptError: print_usage_and_exit()

        # Set our plot flags
	for opt, value in opts:
		if '-1' in opt: plotOnebit = not plotOnebit
		elif '-2' in opt: plotTwobit = not plotTwobit
		elif '-4' in opt: plotFourbit = not plotFourbit
		elif '-t' in opt: GNUPLOT_title = value
		elif '-x' in opt: GNUPLOT_xmin = value
		elif '-X' in opt: GNUPLOT_xmax = value
		elif '-b' in opt: GNUPLOT_BARE_TITLES = 1
		elif '-y' in opt: GNUPLOT_ymin = value
		elif '-Y' in opt: GNUPLOT_ymax = value
		elif '-K' in opt: GNUPLOT_KEY = value
		elif '-c' in opt: COLOR = True
		elif '-m' in opt: MEAN = True
		elif '-R' in opt: RunTitles = False
		elif '-M' in opt: MeanTitles = False
	
	if not args: print_usage_and_exit()

	for arg in args[:]:		# for each argument
		arg = arg.rstrip('/')	# remove the slash
		if not os.path.isdir( arg ): args.remove( arg )			# remove all arguments that aren't directories
		else:
			filename = os.path.abspath(arg) + '/' + FILENAME
			FILENAMES.append( filename )				# else, put it into the FILENAMES
			GNUPLOT_TITLES[filename] = arg				# the arg will be the title

			# if this is a PASSIVE RUN, make it dashed.
			LockStepWithBirthsDeaths = int( common_functions.read_worldfile_parameter( arg + '/worldfile', 'LockStepWithBirthsDeathsLog' ) )

#			print "LOCKSTEPwithBirths=%s" % ( LockStepWithBirthsDeaths ) 
			if LockStepWithBirthsDeaths: GNUPLOT_LINETYPES[filename] = 2
			else: GNUPLOT_LINETYPES[filename] = 1

check_parameters( sys.argv[1:] )                # don't send it the first item in the sys.argv list because that's this programs filename

#print "FILENAMES=%s" % ( FILENAMES )

GNUPLOT_SETTINGS="""
set term aqua dashed dl 0.5
set ylabel '%s' font "Times,15"
set xlabel 'Timestep' font "Times,15"
set grid
set mxtics 5
set title '%s' font "Times,20"
set xrange[%s:%s]
set yrange[%s:%s]
set key %s
""" % ( GNUPLOT_ylabel, GNUPLOT_title, GNUPLOT_xmin, GNUPLOT_xmax, GNUPLOT_ymin, GNUPLOT_ymax, GNUPLOT_KEY )
#""" % ( GNUPLOT_ylabel, GNUPLOT_title, GNUPLOT_xmin, GNUPLOT_xmax, GNUPLOT_ymin, GNUPLOT_ymax )

linecolor, plotstring = 1, ['plot']
for linetype in 1,2:
	if COLOR: linecolor = 1
	else: linecolor = 0
	for filename in FILENAMES:
		if GNUPLOT_LINETYPES[filename] != linetype: continue;	# if this isn't the run where we process this linetype, don't do anything

		if plotOnebit:
			if RunTitles:
				if GNUPLOT_BARE_TITLES: title = GNUPLOT_TITLES[filename]
				else: title = '%s: 1-bit' % ( GNUPLOT_TITLES[filename])
			else:
				title = ''
			#print "Appending runfile \"%s\" to plotstring with title \"%s\"" % ( filename, title )
			plotstring.append( "'%s' using 1:2 with lines linecolor %s linetype %s linewidth %s title '%s'," % ( filename, linecolor, linetype, LINEWIDTH, title) )
			if COLOR: linecolor += 1
		if plotTwobit:
			if not RunTitles: title = ""
			elif GNUPLOT_BARE_TITLES: title = GNUPLOT_TITLES[filename]
			else: title = '%s: 1-bit' % ( GNUPLOT_TITLES[filename])
			plotstring.append( "'%s' using 1:3 with lines linecolor %s linetype %s linewidth %s title '%s'," % ( filename, linecolor, linetype, LINEWIDTH, title) )
			if COLOR: linecolor += 1
		if plotFourbit:
			if not RunTitles: title = ""
			elif GNUPLOT_BARE_TITLES: title = GNUPLOT_TITLES[filename]
			else: title = '%s: 1-bit' % ( GNUPLOT_TITLES[filename])
			plotstring.append( "'%s' using 1:4 with lines linecolor %s linetype %s linewidth %s title '%s'," % ( filename, linecolor, linetype, LINEWIDTH, title) )
			if COLOR: linecolor += 1

#print "Plotting"
if MEAN:
	runcount = {}
	mean = {}
	time = {}
	#print "Plotting the means"
	# Error check
	if plotTwobit or plotFourbit: print "Mean values currently only plotted for 1-bit"

	if plotOnebit:
		#print "Plotting the 1-bit means"
		# Initialize
		for linetype in 1,2:
			lineindex = linetype - 1
			runcount[lineindex] = 0
			mean[lineindex] = {}
	
		# Calculate the means (really the sums at this point; normalized later)
		for filename in FILENAMES:
			linetype = GNUPLOT_LINETYPES[filename]
			lineindex = linetype - 1
			runcount[lineindex] += 1
			file = open( filename )
			i = -1	# so we will ignore the first line
			for line in file:
				if i >= 0:
					line_array = line.split()
					t = int( line_array[0] )
					if runcount[lineindex] > 1:
						mean[lineindex][i] += float( line_array[1] )
						if time[i] != t:
							print "Error: All runs must have the same number of time steps to calculate and display mean values"
							sys.exit(1)
					else:
						mean[lineindex][i] = float( line_array[1] )
						time[i] = t
				i += 1
			file.close()
	
		# Normalize and write out the mean values to temp files
		meanfilename = {}
		for linetype in 1,2:
			lineindex = linetype - 1
			meanfilename[lineindex] = ",temp_%d" % ( linetype )
			tempfile = open( meanfilename[lineindex], 'w' )
			for i in range(len(time)):
				mean[lineindex][i] /= runcount[lineindex]
				string = "%d %g\n" % ( time[i], mean[lineindex][i] )
				tempfile.write( string )
		
		# Append the plot strings to plot the means
		for linetype in 1,2:
			lineindex = linetype - 1
			if MeanTitles:
				if GNUPLOT_BARE_TITLES: title = GNUPLOT_MEAN_TITLES[lineindex]
				else: title = GNUPLOT_MEAN_TITLES[lineindex] + ": 1-bit"
			else:
				title = ''
			#print "Appending meanfile \"%s\" to plotstring with title \"%s\"" % ( meanfilename[lineindex], title )
			plotstring.append( "'%s' using 1:2 with lines linecolor %s linetype %s linewidth %s title '%s'," % ( meanfilename[lineindex], -1, linetype, MEANLINEWIDTH, title ) )

plotstring = ' '.join(plotstring).rstrip(', ')

#print "plotstring=%s" % ( plotstring )
tempfile=open( tempfilename, 'w' )
tempfile.write( GNUPLOT_SETTINGS )
tempfile.write( "\n" )
tempfile.write( plotstring )
tempfile.close()
print "- Executing '%s'" % ( tempfilename )
os.system( 'gnuplot '+ tempfilename )

print "Done!"

