conf=../../../Makefile.conf
include ${conf}

target=${QTCLUST_TARGET}
blddir=${QTCLUST_BLDDIR}

cxxflags=${CXXFLAGS} ${GSL_CXXFLAGS} ${OMP_CXXFLAGS} ${ZIP_CXXFLAGS}
libs=${GSL_LIBS} ${OMP_LIBS} ${ZIP_LIBS}

include ${TARGET_MAK}